name: bump outdated formulae
on:
  workflow_dispatch:

jobs:
  bump-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v5
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          no_fork: true
          tap: nick-f/homebrew-labs
          livecheck: true
