name: update tap
on:
  workflow_dispatch:

jobs:
  update-tap:
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v5
        with:
          # requires a personal access token
          token: ${{ secrets.TOKEN }}
          tap: nick-f/homebrew-labs
          force: false
          no_fork: true
          livecheck: true
